# Generated by Django 4.2.7 on 2023-12-22 16:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('meetings', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='meeting',
            name='subject',
        ),
        migrations.AddField(
            model_name='meeting',
            name='topic',
            field=models.CharField(default=1, max_length=200),
            preserve_default=False,
        ),
    ]
